chore: add upper limit to iface name in linkrename

diff --git a/virtual/linkrename b/virtual/linkrename
--- a/virtual/linkrename
+++ b/virtual/linkrename
@@ -8,6 +8,12 @@ set -e
 echo "SRC=$SRC"
 echo "DST=$DST"
 
+DSTMAXLEN=14
+if [ ${#DST} -ge $DSTMAXLEN ]; then
+ echo "error: expect [$DST] to be less than $DSTMAXLEN bytes."
+ exit 1
+fi
+
 ip link set "$SRC" down
 ip link set "$SRC" name "$DST" || ip link set "$SRC" up
 ip link set "$DST" up
